import re
import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.features.analysis.models import EventAnalysis
from app.features.events.models import DevelopmentEvent
from app.features.project_context.service import get_or_create_project_context
from app.features.projects.models import Project
from app.features.sessions.models import Session

# Redaction patterns for defense-in-depth against secret exposure
SECRET_PATTERNS = [
    re.compile(
        r"(api[_-]?key|secret|token|password|passwd|auth[_-]?token)\s*[:=]\s*['\"][^'\"]+['\"]",
        re.IGNORECASE,
    ),
    re.compile(
        r"(ghp_[A-Za-z0-9_]{36,}|sk-[A-Za-z0-9_-]{20,}|AKIA[0-9A-Z]{16})",
        re.IGNORECASE,
    ),
]


def redact_sensitive_text(text: str) -> str:
    """Ensure no raw tokens or credentials ever slip into the markdown export."""
    if not text:
        return text
    redacted = text
    for pat in SECRET_PATTERNS:
        redacted = pat.sub(r"\1: [REDACTED]", redacted)
    return redacted


def format_iso(dt: datetime | str | None) -> str:
    if not dt:
        return "Unknown"
    if isinstance(dt, str):
        return dt
    return dt.isoformat()


async def generate_project_context_markdown(db: AsyncSession, project_id: uuid.UUID) -> str:
    """
    Generates a canonical, professional, and portable PROJECT_CONTEXT.md document
    derived deterministically from stored PostgreSQL telemetry, project_contexts,
    sessions, events, and analyses.
    """
    project = await db.get(Project, project_id)
    if not project:
        raise ValueError(f"Project with ID {project_id} not found")

    # Fetch latest durable context
    context = await get_or_create_project_context(db, project_id)

    # Fetch recent sessions (last 10)
    sess_stmt = (
        select(Session)
        .where(Session.project_id == project_id)
        .order_by(Session.started_at.desc())
        .limit(10)
    )
    sess_res = await db.execute(sess_stmt)
    sessions = sess_res.scalars().all()

    # Fetch security investigations / event analyses
    analyses_stmt = (
        select(EventAnalysis, DevelopmentEvent)
        .join(DevelopmentEvent, EventAnalysis.event_id == DevelopmentEvent.id)
        .where(
            DevelopmentEvent.project_root == project.root_path,
            EventAnalysis.analyzer_name == "security_guardian",
        )
        .order_by(EventAnalysis.created_at.desc())
        .limit(15)
    )
    analyses_res = await db.execute(analyses_stmt)
    analyses_rows = analyses_res.all()

    now = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    # ─────────────────────────────────────────────────────────────────────────
    # 1. Project Identity & Executive Summary
    # ─────────────────────────────────────────────────────────────────────────
    lang_names = list(context.languages.keys())
    fw_names = [f.name for f in context.frameworks]

    tech_stack_phrase = (
        ", ".join(fw_names or lang_names) if (fw_names or lang_names) else "Standard Software"
    )
    exec_summary_observed = (
        f"VibePulse observed this project as a {tech_stack_phrase} application "
        f"with {context.activity_summary.total_events} recorded development events across "
        f"{context.activity_summary.total_sessions} continuous development sessions."
    )

    if fw_names:
        exec_summary_inferred = (
            f"Detected architecture utilizes {', '.join(fw_names)} for core application "
            f"workflows and modular components based on structural directory layouts "
            f"and manifest files."
        )
    else:
        exec_summary_inferred = (
            "Architecture structure partially observed based on current event activity."
        )

    exec_summary_unknown = (
        "Production deployment infrastructure, external cloud orchestrators, "
        "and business domain requirements are not yet observed from telemetry."
    )

    lines: list[str] = [
        "# Project Context",
        "",
        "> Generated by VibePulse Project Context Memory",
        "",
        "## 1. Project Identity",
        "",
        f"- **Project Name**: `{project.display_name}`",
        f"- **Project Root**: `{project.root_path}`",
        f"- **Project ID**: `{project.id}`",
        f"- **Context Version**: `v{context.context_version}`",
        f"- **First Observed**: `{format_iso(context.first_observed_at)}`",
        f"- **Last Analyzed**: `{format_iso(context.last_analyzed_at)}`",
        f"- **Last Activity**: `{format_iso(context.activity_summary.latest_observed_at)}`",
        "",
        "## 2. Executive Summary",
        "",
        "### Observed",
        f"{exec_summary_observed}",
        "",
        "### Inferred",
        f"{exec_summary_inferred}",
        "",
        "### Unknown",
        f"{exec_summary_unknown}",
        "",
        "---",
        "",
        "## 3. Languages",
        "",
    ]

    # ─────────────────────────────────────────────────────────────────────────
    # 2. Technology Stack & Languages
    # ─────────────────────────────────────────────────────────────────────────
    if context.languages:
        lines.extend(
            [
                "| Language | Observed Events | Share |",
                "|---|---|---|",
            ]
        )
        for lang_name, lang_info in context.languages.items():
            lines.append(f"| {lang_name} | {lang_info.count} | {lang_info.percentage}% |")
        lines.append("")
    else:
        lines.append("No programming language files observed yet.\n")

    lines.extend(
        [
            "## 4. Frameworks",
            "",
        ]
    )
    if context.frameworks:
        for fw in context.frameworks:
            lines.append(f"### {fw.name}")
            lines.append(f"- **Category**: {fw.category}")
            if fw.provenance:
                lines.append(f"- **Detected From**: `{fw.provenance.source}`")
                lines.append(f"- **Evidence**: {fw.provenance.evidence}")
                lines.append(f"- **Detection Type**: `{fw.provenance.detection_type}`")
            lines.append("")
    else:
        lines.append("No third-party frameworks detected yet.\n")

    lines.extend(
        [
            "## 5. Technologies",
            "",
        ]
    )
    if context.technologies:
        for tech in context.technologies:
            lines.append(f"- **{tech.name}** ({tech.category})")
            if tech.provenance:
                ev_str = f"`{tech.provenance.source}` — {tech.provenance.evidence}"
                lines.append(f"  - *Evidence*: {ev_str}")
        lines.append("")
    else:
        lines.append("No specific external technology runtimes detected yet.\n")

    lines.extend(
        [
            "## 6. Package Managers",
            "",
        ]
    )
    if context.package_managers:
        for pm in context.package_managers:
            lines.append(f"- **{pm.name}** ({pm.category})")
            if pm.provenance:
                lines.append(f"  - *Manifest*: `{pm.provenance.source}` ({pm.provenance.evidence})")
        lines.append("")
    else:
        lines.append("No package manager lockfiles or manifests observed.\n")

    # ─────────────────────────────────────────────────────────────────────────
    # 3. Project Structure
    # ─────────────────────────────────────────────────────────────────────────
    lines.extend(
        [
            "---",
            "",
            "## 7. Important Files",
            "",
        ]
    )
    if context.important_files:
        lines.extend(
            [
                "| File Path | Role / Reason | Activity Count | Last Observed |",
                "|---|---|---|---|",
            ]
        )
        for f in context.important_files:
            last_mod_str = format_iso(f.last_modified)
            lines.append(f"| `{f.path}` | {f.reason} | {f.activity_count} | {last_mod_str} |")
        lines.append("")
    else:
        lines.append("No files tracked yet.\n")

    lines.extend(
        [
            "## 8. Configuration Files",
            "",
        ]
    )
    if context.configuration_files:
        for cfg in context.configuration_files:
            lines.append(f"- `{cfg.path}` — *{cfg.kind}*")
        lines.append("")
    else:
        lines.append("No configuration manifests observed.\n")

    lines.extend(
        [
            "## 9. Source Directories",
            "",
        ]
    )
    if context.source_directories:
        for sdir in context.source_directories:
            lines.append(f"- `{sdir}`")
        lines.append("")
    else:
        lines.append("No standard source directories identified yet.\n")

    lines.extend(
        [
            "## 10. Test Directories",
            "",
        ]
    )
    if context.test_directories:
        for tdir in context.test_directories:
            lines.append(f"- `{tdir}`")
        lines.append("")
    else:
        lines.append("No test suites or test directories observed.\n")

    # ─────────────────────────────────────────────────────────────────────────
    # 4. Architecture & Development Patterns
    # ─────────────────────────────────────────────────────────────────────────
    arch = context.architecture_summary
    source_roots_str = (
        f"- **Source Roots**: {', '.join([f'`{r}`' for r in arch.source_roots])}"
        if arch.source_roots
        else "- **Source Roots**: None observed"
    )
    test_roots_str = (
        f"- **Test Roots**: {', '.join([f'`{t}`' for t in arch.test_roots])}"
        if arch.test_roots
        else "- **Test Roots**: None observed"
    )
    modules_str = (
        f"- **Tracked Modules**: {', '.join([f'`{m}`' for m in arch.modules])}"
        if arch.modules
        else "- **Tracked Modules**: None observed"
    )

    lines.extend(
        [
            "---",
            "",
            "## 11. Architecture Summary",
            "",
            f"- **Project Topology**: `{arch.project_type}`",
            source_roots_str,
            test_roots_str,
            modules_str,
            f"- **Active Git Branch**: `{context.git_context.branch or 'N/A'}`",
            "",
            "## 12. Development Patterns",
            "",
        ]
    )
    if context.development_patterns:
        for pat in context.development_patterns:
            lines.append(f"### {pat.name}")
            lines.append(f"{pat.description}")
            lines.append(f"- **Evidence Count**: {pat.evidence_count} events")
            if pat.sample_files:
                sample_str = ", ".join([f"`{sf}`" for sf in pat.sample_files])
                lines.append(f"- **Sample Files**: {sample_str}")
            lines.append("")
    else:
        lines.append("No recurring development patterns detected yet.\n")

    # ─────────────────────────────────────────────────────────────────────────
    # 5. Security Posture
    # ─────────────────────────────────────────────────────────────────────────
    sec = context.security_summary
    rules_str = ", ".join([f"`{r}`" for r in sec.top_rules]) if sec.top_rules else "None"
    redact_note = (
        "- **Redaction Status**: `Enforced` (All raw secrets and tokens are "
        "strictly redacted to `[REDACTED]`)"
    )

    lines.extend(
        [
            "---",
            "",
            "## 13. Security Posture",
            "",
            f"- **Total Findings**: `{sec.total_findings}`",
            f"- **Critical Risk**: `{sec.critical}`",
            f"- **High Risk**: `{sec.high}`",
            f"- **Medium Risk**: `{sec.medium}`",
            f"- **Low Risk**: `{sec.low}`",
            f"- **Top Triggered Rules**: {rules_str}",
            redact_note,
            "",
        ]
    )

    # ─────────────────────────────────────────────────────────────────────────
    # 6. Activity & Development History
    # ─────────────────────────────────────────────────────────────────────────
    act = context.activity_summary
    lines.extend(
        [
            "---",
            "",
            "## 14. Activity Summary",
            "",
            f"- **Total Recorded Events**: `{act.total_events}`",
            f"- **Total Recorded Sessions**: `{act.total_sessions}`",
            f"- **First Activity Recorded**: `{format_iso(act.first_observed_at)}`",
            f"- **Latest Activity Recorded**: `{format_iso(act.latest_observed_at)}`",
            "",
            "## 15. Development History",
            "",
        ]
    )

    if sessions:
        lines.extend(
            [
                "| Session ID | Started At | Events | Status | Dominant Languages |",
                "|---|---|---|---|---|",
            ]
        )
        for s in sessions:
            langs = list((s.languages or {}).keys())
            lang_str = ", ".join(langs) if langs else "N/A"
            s_time = format_iso(s.started_at)
            s_short = f"{str(s.id)[:8]}..."
            lines.append(
                f"| `{s_short}` | {s_time} | {s.event_count} | `{s.status}` | {lang_str} |"
            )
        lines.append("")
    else:
        lines.append("No historical sessions recorded.\n")

    # ─────────────────────────────────────────────────────────────────────────
    # 7. Investigation History
    # ─────────────────────────────────────────────────────────────────────────
    lines.extend(
        [
            "## 16. Security / Investigation History",
            "",
        ]
    )

    if analyses_rows:
        lines.extend(
            [
                "| Timestamp | Analyzer / Rule | File Target | Risk Assessment |",
                "|---|---|---|---|",
            ]
        )
        for analysis, event in analyses_rows:
            findings_dict = analysis.findings if isinstance(analysis.findings, dict) else {}
            rule = findings_dict.get("rule_id", "SEC001")
            score = findings_dict.get("risk_score", 0)
            f_path_tail = event.file_path.split("/")[-1] if event.file_path else "unknown"
            file_name = event.file_name or f_path_tail
            t_str = format_iso(analysis.created_at)
            lines.append(f"| {t_str} | `{rule}` | `{file_name}` | Risk Score: `{score}` |")
        lines.append("")
    else:
        lines.append("No critical security investigations or findings recorded.\n")

    # ─────────────────────────────────────────────────────────────────────────
    # 8. AI Handoff Context
    # ─────────────────────────────────────────────────────────────────────────
    pattern_names = (
        ", ".join([p.name for p in context.development_patterns])
        if context.development_patterns
        else "General Feature Development"
    )
    lang_str = ", ".join(lang_names) if lang_names else "General"
    file_count = len(context.important_files)
    src_dir_count = len(context.source_directories)

    lines.extend(
        [
            "---",
            "",
            "# AI Handoff Context",
            "",
            "## What VibePulse Knows",
            f"1. Verified repository root path is `{project.root_path}`.",
            f"2. Verified active language ecosystem: {lang_str}.",
            f"3. Verified project structure: {file_count} files across {src_dir_count} roots.",
            f"4. Verified {sec.total_findings} security events analyzed with AST guardrails.",
            "",
            "## What VibePulse Inferred",
            f"1. Primary engineering emphasis: {pattern_names}.",
            f"2. Application topology: {arch.project_type}.",
            "",
            "## Unknown / Not Yet Observed",
            "- **Deployment Infrastructure**: Container orchestration is unobserved.",
            "- **Production Configuration**: Live secrets are intentionally excluded.",
            "- **Business Domain Rules**: Functional user requirements are unobserved.",
            "",
            "## Recommended First Questions for an AI Agent",
            f"1. What is the target runtime for `{project.display_name}` (Local, AWS, Docker)?",
            "2. Are there specific linting or architectural rules that changes must satisfy?",
            "3. Which modules are production-critical and require backwards compatibility?",
            "4. Which test suite should be executed to validate new feature changes?",
            "",
            "---",
            "",
            "## Context Provenance",
            "",
            "This context was generated deterministically from:",
            "- PostgreSQL `project_contexts` table",
            f"- `{act.total_events}` recorded development events",
            f"- `{act.total_sessions}` recorded development sessions",
            f"- `{sec.total_findings}` stored security investigation findings",
            "- Observed filesystem artifacts and configuration manifests",
            "",
            f"- **Context Version**: `v{context.context_version}`",
            f"- **Generated At**: `{now}`",
            f"- **Last Analyzed**: `{format_iso(context.last_analyzed_at)}`",
            f"- **Event Count Used**: `{act.total_events}`",
            f"- **Session Count Used**: `{act.total_sessions}`",
            "",
        ]
    )

    raw_doc = "\n".join(lines)
    return redact_sensitive_text(raw_doc)
